export const provinciasPorPais: any = {
	Argentina: [
		'Ciudad Autónoma de Buenos Aires',
		'Buenos Aires',
		'Catamarca',
		'Chaco',
		'Chubut',
		'Córdoba',
		'Corrientes',
		'Entre Ríos',
		'Formosa',
		'Jujuy',
		'La Pampa',
		'La Rioja',
		'Mendoza',
		'Misiones',
		'Neuquén',
		'Río Negro',
		'Salta',
		'San Juan',
		'San Luis',
		'Santa Cruz',
		'Santa Fe',
		'Santiago del Estero',
		'Tierra del Fuego',
		'Tucumán',
	],
	Bolivia: ['Beni', 'Chuquisaca', 'Cochabamba', 'La Paz', 'Oruro', 'Pando', 'Potosí', 'Santa Cruz', 'Tarija'],
	Chile: [
		'Arica y Parinacota',
		'Tarapacá',
		'Antofagasta',
		'Atacama',
		'Coquimbo',
		'Valparaíso',
		'Región Metropolitana de Santiago',
		"O'Higgins",
		'Maule',
		'Ñuble',
		'Biobío',
		'Araucanía',
		'Los Ríos',
		'Los Lagos',
		'Aysén',
		'Magallanes y la Antártica Chilena',
	],
	Colombia: [
		'Amazonas',
		'Antioquia',
		'Arauca',
		'Atlántico',
		'Bolívar',
		'Boyacá',
		'Caldas',
		'Caquetá',
		'Casanare',
		'Cauca',
		'Cesar',
		'Chocó',
		'Córdoba',
		'Cundinamarca',
		'Guainía',
		'Guaviare',
		'Huila',
		'La Guajira',
		'Magdalena',
		'Meta',
		'Nariño',
		'Norte de Santander',
		'Putumayo',
		'Quindío',
		'Risaralda',
		'San Andrés y Providencia',
		'Santander',
		'Sucre',
		'Tolima',
		'Valle del Cauca',
		'Vaupés',
		'Vichada',
	],
	'Costa Rica': ['Alajuela', 'Cartago', 'Guanacaste', 'Heredia', 'Limón', 'Puntarenas', 'San José'],
	Ecuador: [
		'Azuay',
		'Bolívar',
		'Cañar',
		'Carchi',
		'Chimborazo',
		'Cotopaxi',
		'El Oro',
		'Esmeraldas',
		'Galápagos',
		'Guayas',
		'Imbabura',
		'Loja',
		'Los Ríos',
		'Manabí',
		'Morona Santiago',
		'Napo',
		'Orellana',
		'Pastaza',
		'Pichincha',
		'Santa Elena',
		'Santo Domingo de los Tsáchilas',
		'Sucumbíos',
		'Tungurahua',
		'Zamora Chinchipe',
	],
	España: [
		'Andalucía',
		'Aragón',
		'Asturias',
		'Baleares',
		'Canarias',
		'Cantabria',
		'Castilla-La Mancha',
		'Castilla y León',
		'Cataluña',
		'Comunidad Valenciana',
		'Extremadura',
		'Galicia',
		'La Rioja',
		'Madrid',
		'Murcia',
		'Navarra',
		'País Vasco',
	],
	Guatemala: [
		'Alta Verapaz',
		'Baja Verapaz',
		'Chimaltenango',
		'Chiquimula',
		'El Progreso',
		'Escuintla',
		'Guatemala',
		'Huehuetenango',
		'Izabal',
		'Jalapa',
		'Jutiapa',
		'Petén',
		'Quetzaltenango',
		'Quiché',
		'Retalhuleu',
		'Sacatepéquez',
		'San Marcos',
		'Santa Rosa',
		'Sololá',
		'Suchitepéquez',
		'Totonicapán',
		'Zacapa',
	],
	Honduras: [
		'Atlántida',
		'Colón',
		'Comayagua',
		'Copán',
		'Cortés',
		'Choluteca',
		'El Paraíso',
		'Francisco Morazán',
		'Gracias a Dios',
		'Intibucá',
		'Islas de la Bahía',
		'La Paz',
		'Lempira',
		'Ocotepeque',
		'Olancho',
		'Santa Bárbara',
		'Valle',
		'Yoro',
	],
	Mexico: [
		'Aguascalientes',
		'Baja California',
		'Baja California Sur',
		'Campeche',
		'Chiapas',
		'Chihuahua',
		'Ciudad de México',
		'Coahuila',
		'Colima',
		'Durango',
		'Guanajuato',
		'Guerrero',
		'Hidalgo',
		'Jalisco',
		'México',
		'Michoacán',
		'Morelos',
		'Nayarit',
		'Nuevo León',
		'Oaxaca',
		'Puebla',
		'Querétaro',
		'Quintana Roo',
		'San Luis Potosí',
		'Sinaloa',
		'Sonora',
		'Tabasco',
		'Tamaulipas',
		'Tlaxcala',
		'Veracruz',
		'Yucatán',
		'Zacatecas',
	],
	Nicaragua: [
		'Boaco',
		'Carazo',
		'Chinandega',
		'Chontales',
		'Estelí',
		'Granada',
		'Jinotega',
		'León',
		'Madriz',
		'Managua',
		'Masaya',
		'Matagalpa',
		'Nueva Segovia',
		'Río San Juan',
		'Rivas',
		'Región Autónoma de la Costa Caribe Norte',
		'Región Autónoma de la Costa Caribe Sur',
	],
	Panama: [
		'Bocas del Toro',
		'Coclé',
		'Colón',
		'Chiriquí',
		'Darién',
		'Herrera',
		'Los Santos',
		'Panamá',
		'Veraguas',
		'Comarca Emberá-Wounaan',
		'Comarca Guna Yala',
		'Comarca Ngäbe-Buglé',
	],
	Paraguay: [
		'Alto Paraguay',
		'Alto Paraná',
		'Amambay',
		'Asunción',
		'Boquerón',
		'Caaguazú',
		'Caazapá',
		'Canindeyú',
		'Central',
		'Concepción',
		'Cordillera',
		'Guairá',
		'Itapúa',
		'Misiones',
		'Ñeembucú',
		'Paraguarí',
		'Presidente Hayes',
		'San Pedro',
	],
	Peru: [
		'Amazonas',
		'Áncash',
		'Apurímac',
		'Arequipa',
		'Ayacucho',
		'Cajamarca',
		'Callao',
		'Cusco',
		'Huancavelica',
		'Huánuco',
		'Ica',
		'Junín',
		'La Libertad',
		'Lambayeque',
		'Lima',
		'Loreto',
		'Madre de Dios',
		'Moquegua',
		'Pasco',
		'Piura',
		'Puno',
		'San Martín',
		'Tacna',
		'Tumbes',
		'Ucayali',
	],
	'El Salvador': [
		'Ahuachapán',
		'Cabañas',
		'Chalatenango',
		'Cuscatlán',
		'La Libertad',
		'La Paz',
		'La Unión',
		'Morazán',
		'San Miguel',
		'San Salvador',
		'San Vicente',
		'Santa Ana',
		'Sonsonate',
		'Usulután',
	],
	Uruguay: [
		'Artigas',
		'Canelones',
		'Cerro Largo',
		'Colonia',
		'Durazno',
		'Flores',
		'Florida',
		'Lavalleja',
		'Maldonado',
		'Montevideo',
		'Paysandú',
		'Río Negro',
		'Rivera',
		'Rocha',
		'Salto',
		'San José',
		'Soriano',
		'Tacuarembó',
		'Treinta y Tres',
	],
	Venezuela: [
		'Amazonas',
		'Anzoátegui',
		'Apure',
		'Aragua',
		'Barinas',
		'Bolívar',
		'Carabobo',
		'Cojedes',
		'Delta Amacuro',
		'Distrito Capital',
		'Falcón',
		'Guárico',
		'La Guaira',
		'Lara',
		'Mérida',
		'Miranda',
		'Monagas',
		'Nueva Esparta',
		'Portuguesa',
		'Sucre',
		'Táchira',
		'Trujillo',
		'Yaracuy',
		'Zulia',
	],
};
