version: '3.8'

services:
  msk-front:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    command: bash -c "cd /app && npm install && npm run docker"
