version: "3.8"
services:
  frontend:
    container_name: frontend
    build:
      context: .
    restart: always
    command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000