export const NEXT_PUBLIC_REBILL_URL = process.env.NEXT_PUBLIC_REBILL_URL;
export const NEXT_PUBLIC_REBILL_API_KEY_TEST =
  process.env.NEXT_PUBLIC_REBILL_API_KEY_TEST;
export const NEXT_PUBLIC_REBILL_API_KEY_PRD =
  process.env.NEXT_PUBLIC_REBILL_API_KEY_PRD;
export const NEXT_PUBLIC_REBILL_ORG_ID_TEST =
  process.env.NEXT_PUBLIC_REBILL_ORG_ID_TEST;
export const NEXT_PUBLIC_REBILL_ORG_ID_PRD =
  process.env.NEXT_PUBLIC_REBILL_ORG_ID_PRD;

//CL
export const NEXT_PUBLIC_REBILL_CL_ORG_ID_PRD =
  process.env.NEXT_PUBLIC_REBILL_CL_ORG_ID_PRD;
export const NEXT_PUBLIC_REBILL_CL_API_KEY_PRD =
  process.env.NEXT_PUBLIC_REBILL_CL_API_KEY_PRD;
export const NEXT_PUBLIC_REBILL_REBILL_CL_FREEMIUM_PRD =
  process.env.NEXT_PUBLIC_REBILL_REBILL_CL_FREEMIUM_PRD;
export const NEXT_PUBLIC_REBILL_REBILL_CL_FREEMIUM_TEST =
  process.env.NEXT_PUBLIC_REBILL_REBILL_CL_FREEMIUM_TEST;

export const NEXT_PUBLIC_REBILL_REBILL_CL_V3_FREEMIUM_PRD =
  process.env.NEXT_PUBLIC_REBILL_REBILL_CL_V3_FREEMIUM_PRD;
export const NEXT_PUBLIC_REBILL_REBILL_CL_V3_FREEMIUM_TEST =
  process.env.NEXT_PUBLIC_REBILL_REBILL_CL_V3_FREEMIUM_TEST;

export const NEXT_PUBLIC_REBILL_CL_PK_PRD =
  process.env.NEXT_PUBLIC_REBILL_CL_PK_PRD;
export const NEXT_PUBLIC_REBILL_CL_PK_TEST =
  process.env.NEXT_PUBLIC_REBILL_CL_PK_TEST;

//UY
export const NEXT_PUBLIC_REBILL_UY_ORG_ID_PRD =
  process.env.NEXT_PUBLIC_REBILL_UY_ORG_ID_PRD;
export const NEXT_PUBLIC_REBILL_UY_API_KEY_PRD =
  process.env.NEXT_PUBLIC_REBILL_UY_API_KEY_PRD;
export const NEXT_PUBLIC_REBILL_REBILL_UY_FREEMIUM_PRD =
  process.env.NEXT_PUBLIC_REBILL_REBILL_UY_FREEMIUM_PRD;
export const NEXT_PUBLIC_REBILL_REBILL_UY_FREEMIUM_TEST =
  process.env.NEXT_PUBLIC_REBILL_REBILL_UY_FREEMIUM_TEST;

export const NEXT_PUBLIC_REBILL_REBILL_UY_V3_FREEMIUM_PRD =
  process.env.NEXT_PUBLIC_REBILL_REBILL_UY_V3_FREEMIUM_PRD;
export const NEXT_PUBLIC_REBILL_REBILL_UY_V3_FREEMIUM_TEST =
  process.env.NEXT_PUBLIC_REBILL_REBILL_UY_V3_FREEMIUM_TEST;

export const NEXT_PUBLIC_REBILL_UY_PK_PRD =
  process.env.NEXT_PUBLIC_REBILL_UY_PK_PRD;
export const NEXT_PUBLIC_REBILL_UY_PK_TEST =
  process.env.NEXT_PUBLIC_REBILL_UY_PK_TEST;
//COP
export const NEXT_PUBLIC_REBILL_COP_ORG_ID_PRD =
  process.env.NEXT_PUBLIC_REBILL_COP_ORG_ID_PRD;
export const NEXT_PUBLIC_REBILL_COP_API_KEY_PRD =
  process.env.NEXT_PUBLIC_REBILL_COP_API_KEY_PRD;
export const NEXT_PUBLIC_REBILL_REBILL_CO_FREEMIUM_PRD =
  process.env.NEXT_PUBLIC_REBILL_REBILL_COP_FREEMIUM_PRD;
export const NEXT_PUBLIC_REBILL_REBILL_CO_FREEMIUM_TEST =
  process.env.NEXT_PUBLIC_REBILL_REBILL_COP_FREEMIUM_TEST;

export const NEXT_PUBLIC_REBILL_REBILL_CO_V3_FREEMIUM_PRD =
  process.env.NEXT_PUBLIC_REBILL_REBILL_CO_V3_FREEMIUM_PRD;
export const NEXT_PUBLIC_REBILL_REBILL_CO_V3_FREEMIUM_TEST =
  process.env.NEXT_PUBLIC_REBILL_REBILL_CO_V3_FREEMIUM_TEST;

export const NEXT_PUBLIC_REBILL_COP_PK_PRD =
  process.env.NEXT_PUBLIC_REBILL_COP_PK_PRD;
export const NEXT_PUBLIC_REBILL_COP_PK_TEST =
  process.env.NEXT_PUBLIC_REBILL_COP_PK_TEST;

//AR
export const NEXT_PUBLIC_REBILL_MP_AR_V3_FREEMIUM_PRD =
  process.env.NEXT_PUBLIC_REBILL_MP_AR_V3_FREEMIUM_PRD;
export const NEXT_PUBLIC_REBILL_MP_AR_V3_FREEMIUM_TEST =
  process.env.NEXT_PUBLIC_REBILL_MP_AR_V3_FREEMIUM_TEST;

export const NEXT_PUBLIC_REBILL_MP_AR_FREEMIUM_PRD =
  process.env.NEXT_PUBLIC_REBILL_MP_AR_FREEMIUM_PRD;
export const NEXT_PUBLIC_REBILL_MP_AR_FREEMIUM_TEST =
  process.env.NEXT_PUBLIC_REBILL_MP_AR_FREEMIUM_TEST;
export const NEXT_PUBLIC_REBILL_STRIPE_BO_FREEMIUM_PRD =
  process.env.NEXT_PUBLIC_REBILL_STRIPE_BO_FREEMIUM_PRD;
export const NEXT_PUBLIC_REBILL_STRIPE_PY_FREEMIUM_PRD =
  process.env.NEXT_PUBLIC_REBILL_STRIPE_PY_FREEMIUM_PRD;
export const NEXT_PUBLIC_REBILL_STRIPE_PE_FREEMIUM_PRD =
  process.env.NEXT_PUBLIC_REBILL_STRIPE_PE_FREEMIUM_PRD;
export const NEXT_PUBLIC_REBILL_STRIPE_CR_FREEMIUM_PRD =
  process.env.NEXT_PUBLIC_REBILL_STRIPE_CR_FREEMIUM_PRD;
export const NEXT_PUBLIC_REBILL_STRIPE_HN_FREEMIUM_PRD =
  process.env.NEXT_PUBLIC_REBILL_STRIPE_HN_FREEMIUM_PRD;
export const NEXT_PUBLIC_REBILL_STRIPE_USD_FREEMIUM_PRD =
  process.env.NEXT_PUBLIC_REBILL_STRIPE_USD_FREEMIUM_PRD;

//MX
export const NEXT_PUBLIC_REBILL_MX_PK_PRD =
  process.env.NEXT_PUBLIC_REBILL_MX_PK_PRD;
export const NEXT_PUBLIC_REBILL_MX_PK_TEST =
  process.env.NEXT_PUBLIC_REBILL_UY_PK_TEST;

export const NEXT_PUBLIC_REBILL_REBILL_MX_V3_FREEMIUM_PRD =
  process.env.NEXT_PUBLIC_REBILL_REBILL_MX_V3_FREEMIUM_PRD;
export const NEXT_PUBLIC_REBILL_REBILL_MX_V3_FREEMIUM_TEST =
  process.env.NEXT_PUBLIC_REBILL_REBILL_MX_V3_FREEMIUM_TEST;

//DEPRECATED
export const NEXT_PUBLIC_REBILL_DEPRECATED_PK_PRD =
  process.env.NEXT_PUBLIC_REBILL_DEPRECATED_PK_PRD;
export const NEXT_PUBLIC_REBILL_DEPRECATED_PK_TEST =
  process.env.NEXT_PUBLIC_REBILL_DEPRECATED_PK_TEST;
