// src/modules/home/components/oportunidades/data.ts

export const cursosMock = [
    {
      id: 1,
      categoria: 'Anestesiología',
      titulo: 'ACCSAP. Programa de actualización en cardiología clínica',
      temas: 10,
      horas: 400,
      inscriptos: 25000,
      certificado: 'American College of Cardiology',
      imagen: '/images/cards/card1.png',
    },
    {
      id: 2,
      categoria: 'Anestesiología',
      titulo: 'Curso de preparación oposiciones de anestesia y reanimación',
      temas: 22,
      horas: 400,
      inscriptos: 20000,
      certificado: 'Tropos',
      imagen: '/images/cards/card2.png',
    },
    {
      id: 3,
      categoria: 'Administracion',
      titulo: 'Curso superior de administración y gestión hospitalaria',
      temas: 12,
      horas: 400,
      inscriptos: 18000,
      certificado: 'Colegio de Médicos de Buenos Aires',
      imagen: '/images/cards/card3.png',
    },
    {
      id: 4,
      categoria: 'Anestesiología',
      titulo: 'Actualidad en diabetes',
      temas: 4,
      horas: 200,
      inscriptos: 20000,
      certificado: 'MSK',
      imagen: '/images/cards/card4.png',
    },
    {
      id: 5,
      categoria: 'Anestesiología',
      titulo: 'Curso superior de neurología clínica',
      temas: 11,
      horas: 300,
      inscriptos: 19500,
      certificado: 'Tropos',
      imagen: '/images/cards/card5.png',
    },
    {
      id: 6,
      categoria: 'Anestesiología',
      titulo: 'Curso de diagnóstico intensivo',
      temas: 14,
      horas: 400,
      inscriptos: 22000,
      certificado: 'Colegio de Médicos de Buenos Aires',
      imagen: '/images/cards/card6.png',
    },
  ];
  