name: Deploy to FTP

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: FTP deployment
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist
          git-ftp-args: --insecure  # Opcional: Añade esto si necesitas desactivar la verificación de certificados SSL
        env:
            FTP_DEPLOY_PATH: ${{ secrets.FTP_DIR_DEV }}  # Especifica la ruta de la carpeta destino en tu servidor FTP
      
