name: FTP Deploy dev.msklatam.tech

on:
  push:
    branches:
      - site

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Define node version

      - name: Install dependencies
        run: npm install

      - name: Build React App TECH
        env:
          VITE_LRT_OR_RTL: ${{ secrets.VITE_LRT_OR_RTL }}
          VITE_MSK_WP_API: ${{ secrets.VITE_MSK_WP_API }}
          VITE_PUBLIC_URL: ${{ secrets.VITE_PUBLIC_URL_TECH }}
          VITE_RECAPTCHA_PK: ${{ secrets.VITE_RECAPTCHA_PK }}
          VITE_REBILL_URL: "https://api.rebill.to/v2"
          VITE_REBILL_ORG_ID_PRD: ${{ secrets.VITE_REBILL_ORG_ID_PRD}}
          VITE_REBILL_API_KEY_PRD: ${{ secrets.VITE_REBILL_API_KEY_PRD}}
          VITE_REBILL_TOKEN_PRD: ${{ secrets.VITE_REBILL_TOKEN_PRD}}
          VITE_REBILL_CL_ORG_ID_PRD: "48c90c85-322c-49d3-8729-a5658d359216"
          VITE_REBILL_CL_API_KEY_PRD: "API_KEY_19dc9d17-8ae5-4b8a-b2a8-26ab514753c1"
          #VITE_REBILL_REBILL_CL_FREEMIUM_PRD: "d43569e3-5721-4046-b2da-599a46cad61d"
          VITE_REBILL_REBILL_CL_FREEMIUM_PRD: "efbf93e4-c662-49dc-b206-40d917400a12"
          VITE_REBILL_UY_ORG_ID_PRD: "5da1986e-296d-47f6-9bcd-150ed84dc881"
          VITE_REBILL_UY_API_KEY_PRD: "API_KEY_c226a907-0226-4de2-b66a-3185c547945d"
          VITE_REBILL_REBILL_UY_FREEMIUM_PRD: "efbf93e4-c662-49dc-b206-40d917400a12"
          VITE_REBILL_COP_ORG_ID_PRD: "15a1c812-d8e1-4ecd-823d-93ca3bf87549"
          VITE_REBILL_COP_API_KEY_PRD: "API_KEY_9b7f3969-4ce4-45a4-920e-d42af9bdfdf2"
          VITE_REBILL_REBILL_COP_FREEMIUM_PRD: "efbf93e4-c662-49dc-b206-40d917400a12"
          #VITE_REBILL_MP_CL_FREEMIUM_PRD: "7064008c-f0e2-476e-8b56-f6e60b7124e1"
          VITE_REBILL_MP_MX_FREEMIUM_PRD: "e47460da-4378-40e7-853c-e42aa527d809"
          VITE_REBILL_MP_AR_FREEMIUM_PRD: "3e22150d-3dee-4fbf-aa21-250a4e2070e0"
          #VITE_REBILL_STRIPE_CO_FREEMIUM_PRD: "efbf93e4-c662-49dc-b206-40d917400a12"
          #VITE_REBILL_STRIPE_UY_FREEMIUM_PRD: "8a4d228a-318e-4893-855c-b0aba27ba1b0"
          VITE_REBILL_STRIPE_BO_FREEMIUM_PRD: "5e32480f-4cb2-4065-8b3c-993f9f1cfdcd"
          VITE_REBILL_STRIPE_PY_FREEMIUM_PRD: "eb97e99a-8ecb-4577-8cda-031e75824439"
          VITE_REBILL_STRIPE_PE_FREEMIUM_PRD: "76cba059-3059-47ad-b2f5-28aeef3f861a"
          VITE_REBILL_STRIPE_CR_FREEMIUM_PRD: "23684c74-23bf-446a-820d-a6ca1b26fc47"
          VITE_REBILL_STRIPE_HN_FREEMIUM_PRD: "57a14ce2-f035-45e0-95ad-433bb3c0369c"
          VITE_REBILL_STRIPE_USD_FREEMIUM_PRD: "837889d6-ac75-4e06-96e7-681d412e7398"
        run: npm run build

      - name: FTP Upload (TECH).
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER_SITEGROUND_TECH }}
          username: ${{ secrets.FTP_USERNAME_SITEGROUND_TECH }}
          password: ${{ secrets.FTP_PASSWORD_SITEGROUND_TECH }}
          local-dir: ./dist/
          server-dir: ${{ secrets.PUBLIC_HTML_SITEGROUND_TECH }}
